# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macOS-latest



steps:

- script: |
    npm list -g --depth=0
    npm install
    npx cordova build ios
  displayName: script

